database:
  sqlite_path: "data/monitoring_status.db"
  host: "10.1.3.201"
  port: 22
  user: "root"
  password: "Zxcasd!@#"
  db: "gpu_monitor"

SQLITE_DB_PATH: '/home/user/check/status.db'

concurrency:
  max_workers: 10

ssh_defaults:
  port: 22
  username: "root"
  timeout: 15

FEISHU_WEBHOOKS:
  hardware_group: "https://open.feishu.cn/open-apis/bot/v2/hook/34dac020-d043-4865-a83d-fb2daaff4349"
  software_group: "https://open.feishu.cn/open-apis/bot/v2/hook/e266c9de-1fb9-4f1e-bf18-9fc267c06a10"
  analytics_group: "https://open.feishu.cn/open-apis/bot/v2/hook/a61990f9-8bcb-458f-bafa-51c0b87199f3"
  table_sync_webhook: "https://infrawaves.feishu.cn/base/automation/webhook/event/EjMcasNdZwU2cmhPB0YcnzTwnmb"