nodes:
  - host: 10.1.3.201
    hostname: node201
    port: 22
    username: root
    password: "Zxcasd!@#"

  - host: 10.1.3.23
    hostname: node23
    port: 22
    username: root
    password: "Zxcasd!@#"