profiles:
  # 策略1: A100, H800
  nvidia:
    description: "Datacenter-grade NVIDIA GPU (e.g., A100, H800)"
    checks:
      system:
        - "system.disk_usage"
        - "system.memory_usage"
        - "system.hw_error"
      gpu:
        - "gpu.count"
        - "gpu.temperature"
        - "gpu.high_temp"
        - "gpu.ecc_soft_error"
        - "gpu.xid_error"
        - "gpu.thermal_slowdown"
        - "gpu.pcie_status"
        - "gpu.nvlink_status"
        - "gpu.gdr_status"
        - "gpu.acs_status"
        - "gpu.fabric_manager_status"
      network:
        - "network.route"
        - "network.ib_device_status"
        - "network.ib_device_count"
        - "network.ip_rule"
      storage:
        - "storage.gpfs"

  # 策略2: 适用于4090
  gpu_nvidia_4090:
    description: "Prosumer-grade NVIDIA GPU (e.g., 4090)"
    checks:
      system:
        - "system.disk_usage"
        - "system.memory_usage"
        - "system.hw_error"
      gpu:
        - "gpu.count"
        - "gpu.temperature"
        - "gpu.high_temp"
        - "gpu.xid_error"
        - "gpu.thermal_slowdown"
        - "gpu.pcie_status"
      network:
        - "network.route"
        - "network.ib_device_status"
        - "network.ib_device_count"
      storage:
        - "storage.gpfs"

  # 策略3: 适用于沐曦GPU服务器
  gpu_muxi_c100:
    description: "Muxi GPU (e.g., C100)"
    checks:
      system:
        - "system.disk_usage"
        - "system.memory_usage"
      gpu:
        - "gpu.muxi.count"
        - "gpu.muxi.temperature"
        - "gpu.muxi.ecc_state"
        - "gpu.muxi.thermal_status"
        - "gpu.muxi.pcie_status"
      network:
        - "network.route"
        - "network.ib_device_status"
        - "network.muxi.metaxlink_status"
      storage:
        - "storage.gpfs"

  # 策略4: 适用于未知节点
  unknown:
    description: "Nodes with unidentified GPUs"
    checks:
      system:
        - "system.disk_usage"
        - "system.memory_usage"
      gpu: []
      network: []
      storage: []
